homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 26.4387
  longitude: -80.1116
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret api_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: "dchassio.duckdns.org:8123"
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
# sun:

# Weather prediction
# sensor:
#   - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Switch
switch:
  - platform: tplink
    host: 192.168.0.152

wemo:
  static:
    - 192.168.153

# Homekit
homekit:

# iOS
ios:

# Ring
ring:
  username: !secret ring_username
  password: !secret ring_password

sensor:
  - platform: ring
    monitored_conditions:
      - last_activity
      - last_ding
      - wifi_signal_category
      - last_motion
  - platform: darksky
    api_key: !secret darksky_api_key
    update_interval: '00:10'
    monitored_conditions:
      - hourly_summary
      - daily_summary
      - temperature
      - apparent_temperature
      - humidity
      - cloud_cover
      - precip_probability
      - precip_intensity_max
      - wind_speed
      - pressure
      - uv_index
  - platform: pollen
    zip_code: "33445"
    monitored_conditions:
      - allergy_index_today
      - disease_average_forecasted
  - platform: pi_hole
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - domains_being_blocked
      - unique_clients
  - platform: cpuspeed
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: processor_use
      - type: load_5m
      - type: since_last_boot
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°F"
    value_template: '{{ (value | multiply(0.001) * 1.8 + 32) | round(1) }}'

device_tracker:
  - platform: tplink
    host: 192.168.0.1
    username: !secret router_username
    password: !secret router_password

binary_sensor:
  - platform: ring

camera:
  - platform: ring

ffmpeg:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
  pihole:
    title: Pi-Hole
    icon: mdi:block-helper
    url: http://hassio.local/admin
